# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-07-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('weigth', models.PositiveIntegerField(default=0)),
                ('line_color', models.CharField(default='#008000', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('region_code', models.PositiveIntegerField()),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Region'),
        ),
        migrations.AddField(
            model_name='edge',
            name='point1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_point1', to='portal.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='point2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_point2', to='portal.Node'),
        ),
    ]
